# -*- coding: utf-8 -*-
"""FP VI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10yhMf1IKWukveKfNh0JWkspelByEw5mp

IMPORT LIBRARY
"""

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import math

url = 'https://raw.githubusercontent.com/ubaiyusuf/VI/master/dataset.csv'
data = pd.read_csv(url)
data.head(5)

pd.value_counts(data['neighbourhood_group'])

#BARPLOT

y_pos = np.arange(data['neighbourhood_group'].nunique())

plt.bar(y_pos, pd.value_counts(data['neighbourhood_group']), align='center', alpha=0.8)
plt.xticks(y_pos, data.neighbourhood_group.unique())
plt.ylabel('Jumlah')
plt.title('Jumlah persewaan tiap daerah')

plt.show()

#PIE CHART
fig = go.Figure(data=[go.Pie(labels=data.room_type.unique(), values=pd.value_counts(data['room_type']), hole=.3)])
fig.show()

#SCATTER
plt.scatter(data['reviews_per_month'], data['price'], c='red', alpha=0.5)
plt.title('Perbandingan rata-rata review tiap bulan dan harga')
plt.xlabel('rata-rata review per bulan')
plt.ylabel('harga sewa')
plt.show()

#SCATTER PLOTLY
d = [dict(
  type = 'scatter',
  x = data['availability_365'].tolist(),
  y = data['number_of_reviews'].tolist(),
  mode = 'markers',
  transforms = [dict(
    type = 'groupby',
    groups = data['neighbourhood_group'],
    styles = [
        dict(target = 'Brooklyn', value = dict(marker = dict(color = 'red'))),
        dict(target = 'Manhattan', value = dict(marker = dict(color = 'yellow'))),
        dict(target = 'Queens', value = dict(marker = dict(color = 'green'))),
        dict(target = 'Staten Island', value = dict(marker = dict(color = 'blue'))),
        dict(target = 'Bronx', value = dict(marker = dict(color = 'purple')))
    ]
  )]
)]

fig_dict = dict(data=d)
pio.show(fig_dict, validate=False)

#MAPBOX
fig = px.scatter_mapbox(data, lat="latitude", lon="longitude", hover_name="name", hover_data=["price", "number_of_reviews"],
                        color="room_type", color_continuous_scale='Magma', zoom=9, height=300)
fig.update_layout(mapbox_style="open-street-map")
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

#BUBBLE CHART
fig = px.scatter(data, x="price", y="reviews_per_month",
	         size="calculated_host_listings_count", color="neighbourhood_group",
                 hover_name="name", log_x=True, size_max=60)
fig.show()

